version: '3'

services:
    ipfs:
        build: ./go-ipfs
        container_name: ipfs
        ports:
            - 5001:5001
            - 4001:4001
            - 8080:8080

    peer:
        build: ./peer
        container_name: peer
        volumes:
            - ./peer/:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
#        depends_on: 
#            - flask
        restart: always
#        links:
#            - flask
